### ISSUE TITLE
문제 난이도 확인 기능

### ISSUE THREAD

**Issue by jwvg0425** [cubelover/BOJ-tier#6]
안녕하세요. 문제 추천기를 굉장히 잘 사용하고 있는 유저입니다. 일단 좋은 사이트 만들어주셔서 너무 감사하다는 말씀부터 드리구요..

오늘 사이트 새 단장한 것 보고 좀 사용하다 보니 난이도별 문제 분류는 볼 수 있는데 내가 푼 문제가 난이도가 어느 정도인지 확인할 수 있는 기능이 없는게 좀 아쉬웠습니다. 문제를 풀고 나서 푼 문제가 별 몇 개짜리 문제로 분류되어 있는지 궁금할 때가 있더라구요. 그래서 난이도를 확인하고 싶은 문제 번호를 입력하면 그 문제 난이도가 있었으면 좋겠다는 생각이 들었습니다.

비슷한 이유에서, Status에서 내가 최근에 푼 문제 목록 옆에 해당 문제 난이도가 같이 뜨면 더 좋을 것 같다는 생각이 들었습니다.

+ 1~100위 외에 랭킹도 확인 가능했으면 좋겠다는 생각이 드네용

**Comment by MoonHyuk** [comment]
paginator가 없어서 그렇지 `https://koosa.ga/ranking/10/` 이런식으로 100위 밖 랭킹도 확인 가능하네요 핫핫

**Comment by cubelover** [comment]
난이도를 확인하고 싶은 문제 번호를 입력하면 그 문제 난이도가 있었으면 좋겠다는 생각이 들었습니다.
* 다소 불편하지만 확장성을 위해 일단 API로 만들었습니다. UI를 좀 더 개선한 것도 추가하겠습니다. https://koosa.ga/api/

Status에서 내가 최근에 푼 문제 목록 옆에 해당 문제 난이도가 같이 뜨면 더 좋을 것 같다는 생각이 들었습니다.
* 추가했습니다.

1~100위 외에 랭킹도 확인 가능했으면 좋겠다는 생각이 드네용
* @MoonHyuk님께서 말씀하신 것처럼 주소창에서 바꾸면 확인이 가능하긴 합니다. 다른 페이지로 이동할 수 있도록 UI를 추가하겠습니다.
