### ISSUE TITLE
문제 난이도 확인 기능2

### ISSUE THREAD

**Issue by sgc109** [cubelover/BOJ-tier#7]
문제의 번호를 입력하면 난이도를 보여주는 기능이 있으면 좋겠다고 생각해서 들어왔는데
아래에 이미 저와 같은 생각을 하신 분이 계시는군요.
지금도 매우 좋은 사이트라고 생각합니다. 그런데 가끔 적당한 난이도의 문제를 뽑아서 
모의 대회를 한다거나 실전 연습을 하고 싶을 때가 있습니다. 특히 ICPC 를 준비할 때
자신의 실력에 맞지 않게 너무 어려운 문제들을 제외하고
적당한 난이도의 기출 문제들만 모아서 풀고 싶다거나 너무 어려운 문제들이 대부분인 대회를 거르고 싶을 때가 있는데 이럴 때에 매우 유용할 것같습니다.
그리고 어떤 여러개의 문제들에 대해 적당한 난이도인 문제들을 뽑고 싶을 때
만약 입력 폼과 버튼이있어서 그 입력 폼에 문제번호를 하나씩 입력해서 버튼을 누를 때마다
그 문제 번호, 이름, 난이도가 하나의 행으로 추가가 되어 표 형태로 난이도 순으로 자동 정렬이 되어
나타난다면 정말 편할 것같습니다.
감사합니다.

**Comment by cubelover** [comment]
https://koosa.ga/tool/?t=prob
