### ISSUE TITLE
[Bug] 로그인 체크를 하지 않는 현상

### ISSUE THREAD

**Issue by joshua-qa** [cubelover/BOJ-tier#9]
[재현 스텝]
1. 존재하지 않는 BOJ 아이디로 로그인 시도
2. Status 메뉴 클릭

[오류 내용]
로그인 체크를 하지 않으며 해당 상황에서 Status 메뉴, Recommends 메뉴 클릭 시 빈 페이지 노출됩니다.

![image](https://user-images.githubusercontent.com/18359200/29347294-9ab0a6ee-8286-11e7-9e35-6f1ed348b86f.png)

![image](https://user-images.githubusercontent.com/18359200/29347297-9f907176-8286-11e7-8ba9-a4b4836ce746.png)

**Comment by cubelover** [comment]
계정을 생성한 지 얼마 안 되었거나 아이디를 바꿔서 DB에 아직 등록이 안 되었을 수 있어 이 경우 로그인에 실패했음을 알리는 것 보다는 세션에 아이디를 저장해 두는 편이 더 나은 것 같아서 그렇게 했습니다.

빈 페이지가 뜨는 것은 해당 유저가 존재하지 않는다는 것을 알려주려고 의도한 사항이었는데, 빈 페이지가 뜨는 것보다 에러 페이지가 뜨는 게 나을 것 같아서 개선해 보았습니다.

혹시 이런 방식(로그인 실패가 뜨지 않고 status 또는 recommends에 들어갔을 때 에러 페이지가 뜨는 것)에 단점이 있을까요?

**Comment by joshua-qa** [comment]
말씀해주신 이슈 (아직 DB 등록이 안된 경우) 때문에, 현재 적용해주신 방식이 괜찮을 것 같습니다.
에러 페이지 정상적으로 노출되는 점 확인하였습니다!
